AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  deep-risk-model
  SAM Template for deep-risk-model Lambda function

Parameters:
  EnvironmentType:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment type for deployment

Mappings:
  EnvironmentConfig:
    dev:
      LogLevel: DEBUG
      MemorySize: 1024
      Timeout: 30
    staging:
      LogLevel: INFO
      MemorySize: 1536
      Timeout: 60
    prod:
      LogLevel: INFO
      MemorySize: 2048
      Timeout: 90

Globals:
  Function:
    Timeout: !FindInMap [EnvironmentConfig, !Ref EnvironmentType, Timeout]
    MemorySize: !FindInMap [EnvironmentConfig, !Ref EnvironmentType, MemorySize]
    Architectures: [arm64]

Resources:
  DeepRiskModelFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: bootstrap
      Runtime: provided.al2
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /risk-model
            Method: post
      Environment:
        Variables:
          RUST_BACKTRACE: 1
          ENVIRONMENT: !Ref EnvironmentType
          LOG_LEVEL: !FindInMap [EnvironmentConfig, !Ref EnvironmentType, LogLevel]
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  DeepRiskModelFunction:
    Description: "Deep Risk Model Lambda Function ARN"
    Value: !GetAtt DeepRiskModelFunction.Arn
  DeepRiskModelApi:
    Description: "API Gateway endpoint URL for Prod stage for Deep Risk Model function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/risk-model/"
  Environment:
    Description: "Deployment environment"
    Value: !Ref EnvironmentType 