AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  deep-risk-model
  SAM Template for deep-risk-model Lambda function

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024

Resources:
  DeepRiskModelFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - arm64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /risk-model
            Method: post
      Environment:
        Variables:
          RUST_BACKTRACE: 1
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  DeepRiskModelFunction:
    Description: "Deep Risk Model Lambda Function ARN"
    Value: !GetAtt DeepRiskModelFunction.Arn
  DeepRiskModelApi:
    Description: "API Gateway endpoint URL for Prod stage for Deep Risk Model function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/risk-model/" 