name: prod
on:
  workflow_dispatch:

environment:
  name: prod
  url: ${{ steps.deployment.outputs.env_url }}

# Protection rules
protection_rules:
  required_reviewers:
    - sethdford  # Replace with your GitHub username
  required_deployments:
    - staging

# Environment variables
env:
  ENVIRONMENT: prod
  LOG_LEVEL: warn 