title: Deep Risk Model
description: A high-performance risk modeling system using transformer-based architecture and hardware-accelerated computations
url: "https://sethdford.github.io/deep-risk-model-v2"
repository: sethdford/deep-risk-model-v2

# Theme settings
theme: just-the-docs
color_scheme: dark

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Deep Risk Model on GitHub":
    - "//github.com/sethdford/deep-risk-model-v2"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Sort order for navigation links
nav_sort: case_sensitive

# External navigation links
nav_external_links:
  - title: Deep Risk Model on GitHub
    url: https://github.com/sethdford/deep-risk-model-v2

# Footer content
footer_content: "Copyright &copy; 2024 Deep Risk Model. Distributed under the <a href=\"https://github.com/sethdford/deep-risk-model-v2/blob/main/LICENSE\">MIT License.</a>"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/sethdford/deep-risk-model-v2"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# Google Analytics
ga_tracking: UA-XXXXXXXXX-X
ga_tracking_anonymize_ip: true

# Callouts
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green

# Heading anchor links
heading_anchors: true

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false 