name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  PYO3_USE_ABI3_FORWARD_COMPATIBILITY: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            features: "--features openblas --no-default-features"
          - os: macos-latest
            features: "--features accelerate --no-default-features"

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Set up Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.os }}
    
    # Install system dependencies for OpenBLAS on Ubuntu
    - name: Install OpenBLAS dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenblas-dev gfortran
    
    # Build with the specified features
    - name: Build
      run: cargo build --verbose ${{ matrix.features }}
    
    # Build examples with the specified features
    - name: Build examples
      run: cargo build --verbose ${{ matrix.features }} --examples
    
    # Run tests with the specified features
    - name: Run tests
      run: cargo test --verbose ${{ matrix.features }}

  build-no-blas:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Set up Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.os }}-no-blas
    
    # Build with no-blas feature
    - name: Build with no-blas
      run: cargo build --verbose --no-default-features --features no-blas
    
    # Build examples with no-blas feature
    - name: Build examples with no-blas
      run: cargo build --verbose --no-default-features --features no-blas --examples
    
    # Run tests with no-blas feature
    - name: Run tests with no-blas
      run: |
        # Ensure we're only using the no-blas feature and not accidentally enabling BLAS
        cargo clean
        cargo test --verbose --no-default-features --features no-blas
